/* eslint-disable no-unused-vars */
export enum Config {
  API_PREFIX = 'API_PREFIX',
  SWAGGER_PREFIX = 'SWAGGER_PREFIX',
  NODE_ENV = 'NODE_ENV',
  HOST = 'HOST',
  BACKEND_HOST ='BACKEND_HOST',
  FRONTEND_HOST ='FRONTEND_HOST',
  PORT = 'PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_HOST = 'DB_HOST',
  DB_HOST_WRITER = 'DB_HOST_WRITER',
  DB_HOST_READER = 'DB_HOST_READER',
  DB_RDS_MODE = 'DB_RDS_MODE',
  JWT_SECRET = 'JWT_SECRET',
}
